package hibernatePackage;

// Generated Mar 13, 2017 10:52:21 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursedata generated by hbm2java
 */
@Entity
@Table(name = "coursedata")
public class Coursedata implements java.io.Serializable {

	private int id;
	private Course course;
	private String lecture;
	private String name;
	private Set<Groupcoursedata> groupcoursedatas = new HashSet<Groupcoursedata>(0);

	public Coursedata() {
	}

	public Coursedata(int id) {
		this.id = id;
	}

	public Coursedata(int id, Course course, String lecture, String name, Set<Groupcoursedata> groupcoursedatas) {
		this.id = id;
		this.course = course;
		this.lecture = lecture;
		this.name = name;
		this.groupcoursedatas = groupcoursedatas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseid")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "lecture", length = 100)
	public String getLecture() {
		return this.lecture;
	}

	public void setLecture(String lecture) {
		this.lecture = lecture;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coursedata")
	public Set<Groupcoursedata> getGroupcoursedatas() {
		return this.groupcoursedatas;
	}

	public void setGroupcoursedatas(Set<Groupcoursedata> groupcoursedatas) {
		this.groupcoursedatas = groupcoursedatas;
	}

}
