package hibernatePackage;

// Generated Mar 16, 2017 2:42:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursedata generated by hbm2java
 */
@Entity
@Table(name = "coursedata")
public class Coursedata implements java.io.Serializable {

	private int id;
	private Course course;
	private Language language;
	private Person person;
	private Integer practice;
	private Integer lecture;
	private Integer excercise;
	private Double lecturesperweek;
	private String semester;
	private Set<Groupcoursedata> groupcoursedatas = new HashSet<Groupcoursedata>(0);

	public Coursedata() {
	}

	public Coursedata(int id) {
		this.id = id;
	}

	public Coursedata(int id, Course course, Language language, Person person, Integer practice, Integer lecture, Integer excercise, Double lecturesperweek, String semester,
			Set<Groupcoursedata> groupcoursedatas) {
		this.id = id;
		this.course = course;
		this.language = language;
		this.person = person;
		this.practice = practice;
		this.lecture = lecture;
		this.excercise = excercise;
		this.lecturesperweek = lecturesperweek;
		this.semester = semester;
		this.groupcoursedatas = groupcoursedatas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseid")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "languageid")
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacherid")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "practice")
	public Integer getPractice() {
		return this.practice;
	}

	public void setPractice(Integer practice) {
		this.practice = practice;
	}

	@Column(name = "lecture")
	public Integer getLecture() {
		return this.lecture;
	}

	public void setLecture(Integer lecture) {
		this.lecture = lecture;
	}

	@Column(name = "excercise")
	public Integer getExcercise() {
		return this.excercise;
	}

	public void setExcercise(Integer excercise) {
		this.excercise = excercise;
	}

	@Column(name = "lecturesperweek", precision = 17, scale = 17)
	public Double getLecturesperweek() {
		return this.lecturesperweek;
	}

	public void setLecturesperweek(Double lecturesperweek) {
		this.lecturesperweek = lecturesperweek;
	}

	@Column(name = "semester", length = 5)
	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coursedata")
	public Set<Groupcoursedata> getGroupcoursedatas() {
		return this.groupcoursedatas;
	}

	public void setGroupcoursedatas(Set<Groupcoursedata> groupcoursedatas) {
		this.groupcoursedatas = groupcoursedatas;
	}

}
