package hibernatePackage;

// Generated Mar 16, 2017 2:42:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Coursedata> coursedatas = new HashSet<Coursedata>(0);

	public Language() {
	}

	public Language(int id) {
		this.id = id;
	}

	public Language(int id, String name, Set<Coursedata> coursedatas) {
		this.id = id;
		this.name = name;
		this.coursedatas = coursedatas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<Coursedata> getCoursedatas() {
		return this.coursedatas;
	}

	public void setCoursedatas(Set<Coursedata> coursedatas) {
		this.coursedatas = coursedatas;
	}

}
